### ISSUE TITLE
do not check the file's extension

### ISSUE THREAD

**Issue by aoloe** [euskadi31/ConfigServiceProvider#1]
would you mind not checking for the extension of the file being `.yml`?
the Yaml component already throws an exception if the file is not a valid yaml file...

**Comment by aoloe** [comment]
somebody could have .yaml or .txt files...

but, in my case, it's because i'm joining multiple .yml files into one temporary file and PHP does not allow me to add an extension when generating a temporary file.

**Comment by euskadi31** [comment]
Hi Aoloe,

Sorry for the wait...

**Comment by aoloe** [comment]
thanks!
